flat_full.Rmd:
  path: dev/flat_full.Rmd
  state: active
  R:
  - R/my_median.R
  - R/my_other_median.R
  tests:
  - tests/testthat/test-my_median.R
  - tests/testthat/test-my_other_median.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_full.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_preprocess_2018.Rmd:
  path: dev/flat_preprocess_2018.Rmd
  state: active
  R:
  - R/audit_categorical_cleaning.R
  - R/clean_opencensus_dob.R
  - R/recode_opensrp_education.R
  - R/preprocess_2018.R
  tests:
  - tests/testthat/test-audit_categorical_cleaning.R
  - tests/testthat/test-clean_opencensus_dob.R
  - tests/testthat/test-recode_opensrp_education.R
  - tests/testthat/test-preprocess_2018.R
  vignettes: vignettes/cohort-2018-preprocessing.Rmd
  inflate:
    flat_file: dev/flat_preprocess_2018.Rmd
    vignette_name: Cohort 2018 Preprocessing
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_tracking_inputs.Rmd:
  path: dev/flat_tracking_inputs.Rmd
  state: active
  R:
  - R/authenticate_google_drive.R
  - R/create_datapaths.R
  - R/download_to_local.R
  - R/has_drive_file_changed.R
  - R/mahery_input_files.R
  tests:
  - tests/testthat/test-authenticate_google_drive.R
  - tests/testthat/test-has_drive_file_changed.R
  - tests/testthat/test-create_datapaths.R
  - tests/testthat/test-download_to_local.R
  vignettes: vignettes/tracking-input-data.Rmd
  inflate:
    flat_file: dev/flat_tracking_inputs.Rmd
    vignette_name: Tracking Input Data
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
