---
title: "flat_preprocess_2019_household_heads.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r setup}
library(here)
library(targets)
tar_load(cohort_2018_households)

# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
library(janitor)
library(dplyr)
library(tidyr)
library(lubridate)
library(skimr)
library(forcats)
library(stringr)
```

Another task is to process the household heads data for 2019. 
This will involve cleaning and transforming the data to make it suitable for analysis,
similar to the 2018 household heads data processing.

To match this, we will need the following columns:

```{r}
cohort_2018_households %>% names()
```

```{r development-preprocess_2019_household_heads}
# Prepare the code of your function here
```

```{r function-preprocess_2019_household_heads}
#' preprocess_2019_household_heads Title
#'
#' @return 1
#' @export
#'
#' @examples
preprocess_2019_household_heads <- function() {
  1
}
```

```{r examples-preprocess_2019_household_heads}
preprocess_2019_household_heads()
```

```{r tests-preprocess_2019_household_heads}
test_that("preprocess_2019_household_heads works", {
  expect_true(inherits(preprocess_2019_household_heads, "function"))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_preprocess_2019_household_heads.Rmd", vignette_name = "Go further")
```

