# WARNING - Generated by {fusen} from dev/flat_preprocess_2019_health.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("preprocess_rdp_health_subset works", {
  expect_true(inherits(preprocess_rdp_health_subset2019, "function")) 
})
