# WARNING - Generated by {fusen} from dev/flat_preprocess_2019_health.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("preprocess_2019_health works", {
  expect_true(inherits(preprocess_2019_health, "function"))
})
