# WARNING - Generated by {fusen} from dev/flat_preprocess_2019.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("clean_dharma_names works", {
  expect_true(inherits(clean_dharma_names, "function")) 
})
