# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("process_deformities works", {
  expect_true(inherits(process_deformities, "function")) 
})
