# WARNING - Generated by {fusen} from dev/flat_preprocess_2019.Rmd: do not edit by hand # nolint: line_length_linter.

#' Clean participant names from DHARMA survey data
#'
#' This function standardizes participant names from the `L1_q1_name` column 
#' by converting them to lowercase, replacing periods with spaces, and removing
#' extra whitespace.
#'
#' @param df A data frame containing a column named `L1_q1_name` with participant names.
#'
#' @return A data frame with an additional column `name_clean` containing the cleaned names.
#'
#' @details The function replaces literal periods (`.`) in names with spaces using 
#' regular expression syntax, then collapses any multiple spaces into one. This is useful 
#' for ensuring consistent formatting in name-based joins or comparisons.
#'
#' @examples
#' df <- tibble::tibble(L1_q1_name = c("ALICE  Smith", " Bob Jones ", "c. miller"))
#' clean_dharma_names(df)
#'
#' @export
clean_dharma_names <- function(df, name_col = L1_q1_name) {
    
  df %>%
    mutate(
      name_clean = {{name_col}} %>%
        str_to_lower() %>%
        str_replace("\\.", " ") %>% # remove the period from names; I don't know why it was allowed in
        str_squish()
    ) 
}
