# WARNING - Generated by {fusen} from dev/flat_preprocess_2019.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
clean_2019_profession <- function(df){

  prof_columns <- names(df) %>%
    str_subset(., "what_occupation|other_occupation")

  df %>%
    select(all_of(prof_columns)) %>%
    mutate(across(everything(), ~ str_replace(., "\\.|Other", NA_character_))) %>%
    unite(occupation, everything(), na.rm=TRUE) -> df_
  
  df %>%
    mutate(employment_status_clean = 
      case_when(
        L1_q12_occupation == "No" ~ "inactive",
        L1_q13_what_occupation.006 == "Student" ~ "not applicable",
        L1_q14_other_occupation == "Tsy miasa" ~ "inactive",
        L1_q12_occupation == "Yes"  ~ "employed",
        TRUE ~ NA_character_

      )
    ) %>%
    mutate(
      occupation = df_$occupation
    ) %>%
    mutate(
      profession_clean = case_when(
        str_detect(str_to_lower(occupation), "^farmer$") ~ "farmer",
        str_detect(str_to_lower(occupation), "shop owner$") ~ "shop owner",
        str_detect(str_to_lower(occupation), "teacher$") ~ "teacher",
        str_detect(str_to_lower(occupation), "student") ~ "student",
        str_detect(str_to_lower(occupation), "manjaitra") ~ "tailor",
        str_detect(str_to_lower(occupation), "mpanjaitra") ~ "tailor",
        str_detect(str_to_lower(occupation), "infirmier") ~ "nurse",
        str_detect(str_to_lower(occupation), "fisher") ~ "fisherman",
        str_detect(str_to_lower(occupation), "assistant") ~ "research assistant",
        str_detect(str_to_lower(occupation), "sage-femme") ~ "midwife",
        str_detect(str_to_lower(occupation), "mpampivelona") ~ "midwife",
        str_detect(str_to_lower(occupation), "mpiasa andakana") ~ "government worker",
        str_detect(str_to_lower(occupation), "government") ~ "government worker",
        str_detect(str_to_lower(occupation), "mpamaky fafana") ~ "fieldworker",
        str_detect(str_to_lower(occupation), "mpanadihady mponina") ~ "fieldworker",
        str_detect(str_to_lower(occupation), "cozan") ~ "government worker",
        str_detect(str_to_lower(occupation), "commissionaire") ~ "assistant",
        str_detect(str_to_lower(occupation), "caretaker") ~ "caretaker",
        str_detect(str_to_lower(occupation), "mpikaraka mpanampy") ~ "caretaker",
        str_detect(str_to_lower(occupation), "mecaniscien") ~ "mechanic",
        str_detect(str_to_lower(occupation), "famme de menage") ~ "housekeeper",
        str_detect(str_to_lower(occupation), "femme de menage") ~ "housekeeper",
        str_detect(str_to_lower(occupation), "sculptures") ~ "sculptor",
        str_detect(str_to_lower(occupation), "charp") ~ "carpenter",
        str_detect(str_to_lower(occupation), "mpandrafitra") ~ "carpenter",
        str_detect(str_to_lower(occupation), "police") ~ "police officer",
        str_detect(str_to_lower(occupation), "chef parsele") ~ "priest",
        str_detect(str_to_lower(occupation), "mpisikidy") ~ "traditional healer",
        str_detect(str_to_lower(occupation), "agent marin") ~ "marine agent",

        TRUE ~ NA_character_
      )
    )
}
