# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Fix known misspellings and assign corrected household head names
#'
#' This function applies hand-curated corrections to a set of known misspelled names in a 
#' data frame. It replaces values in the specified `name_col` with standardized spellings 
#' using a hard-coded correction map. In addition, it conditionally renames household heads 
#' in both the `name_col` and `hh_col` columns for specific known ID patterns.
#'
#' @param df A data frame containing at least a name column, a household head name column,
#' and an `id` column used for conditional overrides.
#' @param name_col The unquoted name of the column in `df` containing the original (possibly misspelled) names.
#' Defaults to `name`.
#' @param hh_col The unquoted name of the column in `df` containing the household head names.
#' Defaults to `hh_head_name`.
#'
#' @return A data frame with standardized name values in `name_col`, and selected rows in `hh_col`
#' updated based on predefined `id` patterns. A new column is not created; the original columns are modified.
#'
#' @details
#' - Known misspellings are replaced based on a hardcoded correction map.
#' - Specific IDs (e.g., those starting with `"A3dd6eda"` and `"48149ba9"`) are assigned known corrected names
#'   directly in both `name_col` and `hh_col`.
#'
#' @examples
#' df <- tibble::tibble(
#'   id = c("A3dd6eda123", "48149ba9111", "otherid"),
#'   name = c("eddy", "unknown", "juliette"),
#'   hh_head_name = c("eddy", "unknown", "juliette")
#' )
#' fix_duplicate_misspelled_names(df)
#'
#' open_census_ %>%
#'   fix_duplicate_misspelled_names(name_col = name_family_member_clean, 
#'                                  hh_col = hh_head_name_clean) -> open_census_
#' @export
fix_duplicate_misspelled_names <- function(df, name_col = name, hh_col = hh_head_name) {
  name_col_sym <- rlang::enquo(name_col)
  hh_col_sym <- rlang::enquo(hh_col)

  # Hand-curated corrections
  correction_map <- tibble::tibble(
    name = c(
      "be jenore", "juliette", "berthine", "bevita", "jean bemiao", 
      "jean erique", "marrgelin", "orelin frasoa", "philippe", 
      "raherimanana jean fredo", "randriamanantena", 
      "ravalomanana junel", "jean yves", "rozadison jean barthelemy",
      "tianavelo zara aime", "avoavy clovis", "zenal ture", "emilien", "geralson", "randrianasoavina"
    ),
    corrected = c(
      "be jenole", "be juliette", "bertine", "bsvita", "jan bemiao",
      "jean ericque", "margelin", "orelin françois", "phillippe",
      "raherimananajean fredo", "randriamanantena honorat",
      "ravalomanana junelle", "renaud", "rozaddison jean barthelemy",
      "tianavelo", "voavy clovis", "zanal ture", "emillien", "geralison", "randrianasoaviana"
    )
  )

  df %>%
    dplyr::left_join(correction_map, by = setNames("name", rlang::as_name(name_col_sym))) %>%
    dplyr::mutate(!!rlang::as_name(name_col_sym) := dplyr::coalesce(corrected, !!name_col_sym)) %>%
    dplyr::select(-corrected) %>%

    # set eddy ii to corrected name
    dplyr::mutate(!!rlang::as_name(name_col_sym) := 
      dplyr::case_when(
        !!name_col_sym == "eddy" & str_starts(id, "A3dd6eda") ~ "eddy ii",
        TRUE ~ !!name_col_sym
      )) %>%
    dplyr::mutate(!!rlang::as_name(hh_col_sym) := 
      dplyr::case_when(
        str_starts(id, "A3dd6eda") ~ "eddy ii",
        str_starts(id, "48149ba9") ~ "kalo jeannette",
        TRUE ~ !!hh_col_sym
      ))
}
