# WARNING - Generated by {fusen} from dev/flat_preprocess_2019_health.Rmd: do not edit by hand # nolint: line_length_linter.

#' RDP Health Subset Preprocessing
#' 
#' This function preprocesses the 2019 data to extract a subset of health-related information.
#' It focuses on cleaning and organizing health data for the RDP paper.
#' 
#' @return
#' 
#' @export
preprocess_rdp_health_subset <- function(dharma2019){
    
    cohort_2019_anthro <- dharma2019$`Level 2 Named`
    dharma2019_dict <- dharma2019$`Data Dictionary`
    level_2_dict <- dharma2019_dict %>%
      filter(level == 2)

    cohort_2019_anthro %>% 
      fill(fact_0_id, fact_1_id, .direction = "down") %>%
      filter(!deleted) %>%
      filter(L2_q38_date_followup != ".") %>%
      mutate(date_clean = L2_q38_date_followup %>%
        na_if("\\.") %>% 
        as.numeric() %>%
        convert_to_date()) -> cohort_2019_anthro_

    cohort_2019_anthro_ %>%
      filter(L2_q47_participate == "Yes") %>%
      filter(L2_q41_alive == "Yes") %>%
      filter(L2_q46_present == "Yes") -> cohort_2019_anthro_
    
    cohort_2019_anthro_ %>%
      mutate(recent_birth_clean = case_when(
        L2_q196_live_birth == "Yes" ~ TRUE,
        L2_q196_live_birth == "No" ~ FALSE,
        L2_q196_live_birth == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) -> cohort_2019_anthro_

    cohort_2019_anthro_ %>%
      mutate(pregnant_now_clean = case_when(
        L2_q200_pregnant_now == "Yes" ~ TRUE,
        L2_q200_pregnant_now == "No" ~ FALSE,
        L2_q200_pregnant_now == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) -> cohort_2019_anthro_

    diagnoses <- level_2_dict %>%
      fill(column_name, .direction = "down") %>%
      filter(str_detect(column_name, "q62_diagnostic")) %>%
      mutate(raw = make_clean_names(choice_name)) %>%
      select(raw) %>%
      left_join(malagasy_diagnosis_lookup_table) %>%
      pull(diagnosis_english) %>%
      str_c("diag_", ., "_clean")

    ind_diagnoses <- names(cohort_2019_anthro_) %>%
      str_detect("q62_diagnostic") %>%
      which()

    names(cohort_2019_anthro_)[ind_diagnoses] <- diagnoses

    cohort_2019_anthro_ %>%

      #diarrhea
      mutate(symptom15dys_diarrhea_clean = case_when(
        L2_q94_diarrhea_now_15days == "Yes" ~ TRUE,
        L2_q94_diarrhea_now_15days == "No" ~ FALSE,
        L2_q94_diarrhea_now_15days == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) %>%

      #fever
      mutate(symptom15dys_fever_clean = case_when(
        L2_q117_fever_now_15days == "Yes" ~ TRUE,
        L2_q117_fever_now_15days == "No" ~ FALSE,
        L2_q117_fever_now_15days == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) %>%

      # emesis
      mutate(symptom15dys_vomit_clean = case_when(
        L2_q137_vomit_now_15days == "Yes" ~ TRUE,
        L2_q137_vomit_now_15days == "No" ~ FALSE,
        L2_q137_vomit_now_15days == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) %>%

      # headache
      mutate(symptom15dys_headache_clean = case_when(
        L2_q236_headache_15days == "Yes" ~ TRUE,
        L2_q236_headache_15days == "No" ~ FALSE,
        L2_q236_headache_15days == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) -> cohort_2019_anthro_
      
    cohort_2019_anthro_ %>%
      mutate(uuid_clean = fact_1_id) %>%
      group_by(uuid_clean) %>%
      arrange(uuid_clean, date_clean) %>%
      mutate(followup_number_clean = row_number()) %>%
      ungroup() %>%
      mutate(across(contains("diag_"), ~ case_when(
        . == "." ~ NA,
        . == NA ~ NA,
        TRUE ~ TRUE
      ) %>% as.factor())) %>%
      rename(village_clean = L2_q791_enumerator) %>%
      select(contains('clean')) %>%
      select(-contains("L2")) %>%
      select(uuid_clean, followup_number_clean, date_clean, village_clean, everything())
}
