# WARNING - Generated by {fusen} from dev/flat_preprocess_2019.Rmd: do not edit by hand # nolint: line_length_linter.

#' preprocess_2019 Title
#'
#' @return 1
#' @export
#'
preprocess_2019 <- function(dharma2019) {
  
  cohort_df <- dharma2019$`Level 1 Named`

  # create household head name
  household_df <- dharma2019$`Level 0 Named` %>%
    select(fact_0_id, L0_q2_hh_name) %>%
    rename(hh_head_name = L0_q2_hh_name) %>%
    distinct() %>%
    mutate(hh_head_name = na_if(hh_head_name,".")) %>%
    filter(!is.na(hh_head_name))

  # some na filtering
  cohort_df %>%
    fill(fact_0_id, .direction = "down") %>%
    filter(!is.na(L1_q39_date)) %>%
    filter(L1_q39_date != ".") %>% 
    filter(!is.na(L1_q1_name)) %>%
    filter(L1_q1_name != ".") %>% 
    filter(!is.na(L1_q1_name)) %>%
    filter(L1_q1_name != ".") %>% 
    filter(!is.na(L1_q8_gender)) %>%
    filter(L1_q8_gender != ".") %>%
    filter(!is.na(L1_q2_dob_year)) %>%
    filter(L1_q2_dob_year != ".") %>%

    #join household head name
    left_join(household_df, by = "fact_0_id") %>%

    #names
    clean_dharma_names() %>%
    #apply same naming cleaning as 2018 cohort; we have to add a dummy id
    # column to match the 2018 cohort
    mutate(id = "") %>%
    fix_duplicate_misspelled_names(name_col = name_clean, hh_col = hh_head_name) %>%
    select(-id) %>%
    #dob
    mutate(
      dob_date = L1_q5_dob_date,
      dob_year = L1_q2_dob_year,
      dob_month = L1_q4_dob_month,
      dob_actual = L1_q6_actual_dob
    ) %>%
    clean_opencensus_dob() %>%
    
    #ethnicity
    mutate(ethnicity_clean = str_to_lower(L1_q10_ethnicity)) %>%

    #education
    mutate(education = str_to_sentence(L1_q169_education) %>% str_replace("Universite", "University") %>% str_replace("\\.|No education", "None")) %>%
    recode_opensrp_education() %>%
    
    #profession
    clean_2019_profession() %>%

    #sex and marital
    mutate(
    sex_clean = str_to_lower(L1_q8_gender) %>%
     str_replace("\\.", NA_character_) %>% 
     as.factor()
    ) %>%
    mutate(
      marital_status_clean = str_to_lower(L1_q15_martial_stat) %>%
        str_replace("\\.", NA_character_) %>%
        as.factor()
    ) %>%

    # create unique ids
    mutate(hh_head_name_clean = hh_head_name %>%
      str_to_lower() %>%
      str_replace("\\.", " ") %>% # remove the period from names; I don't know why it was allowed in
      str_squish()
    ) %>%
    mutate(age_group_clean = calculate_age_group(dob_clean)) %>%
    select(contains("clean")) %>%
    select(-dob_date_clean, -dob_month_clean) %>%
    rename_all(~ str_replace(., "_clean", "")) %>%
    rowwise() %>%
    mutate(uuid = generate_uid(salt=Sys.getenv("UUID_SALT"), name, hh_head_name, as.character(dob), sex)) %>%
    ungroup()
}
