# WARNING - Generated by {fusen} from dev/flat_preprocess_2019_health.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
#' @examples
#' preprocess_rdp_health_subset2020(dharma2020, dharma2019$`Data Dictionary`) %>%
#'   skim()
preprocess_rdp_health_subset2020 <- function(dharma2020, dharma2019_dict){
    
    cohort_2020_anthro <- dharma2020
    
    dharma2019_dict %>%
      fill(column_name, level, .direction = "down") %>%
      fill(level, .direction = "down")  -> dharma2019_dict
    level_2_dict <- dharma2019_dict %>%
      filter(level == 2)

    cohort_2020_anthro %>% 
      # fill(fact_0_id, fact_1_id, .direction = "down") %>%
      filter(!deleted) %>%
      filter(L0_q38_date_followup != ".") %>%
      mutate(date_clean = L0_q38_date_followup %>%
        na_if("\\.") %>% 
        dmy_hms()) -> cohort_2020_anthro_

    cohort_2020_anthro_ %>%
      filter(L0_q47_participate == "Yes") %>%
      filter(L0_q41_alive == "Yes") %>%
      filter(L0_q46_present == "Yes") -> cohort_2020_anthro_
    
    cohort_2020_anthro_ %>%
      mutate(recent_birth_clean = case_when(
        L0_q196_live_birth == "Yes" ~ TRUE,
        L0_q196_live_birth == "No" ~ FALSE,
        L0_q196_live_birth == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) -> cohort_2020_anthro_

    cohort_2020_anthro_ %>%
      mutate(pregnant_now_clean = case_when(
        L0_q200_pregnant_now == "Yes" ~ TRUE,
        L0_q200_pregnant_now == "No" ~ FALSE,
        L0_q200_pregnant_now == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) -> cohort_2020_anthro_

    diagnoses <- level_2_dict %>%
      
      filter(str_detect(column_name, "q62_diagnostic")) %>%
      mutate(raw = make_clean_names(choice_name)) %>%
      select(raw) %>%
      left_join(malagasy_diagnosis_lookup_table) %>%
      pull(diagnosis_english) %>%
      str_c("diag_", ., "_clean")

    ind_diagnoses <- names(cohort_2020_anthro_) %>%
      str_detect("q62_diagnostic") %>%
      which()

    if(length(ind_diagnoses) != length(diagnoses)){
      stop("number of diagnoses does not match number of diagnosis columns in 2020 data")
    }

    names(cohort_2020_anthro_)[ind_diagnoses] <- diagnoses

    cohort_2020_anthro_ %>%

      # malaria
      mutate(diag_malaria_rdt_positive_clean = case_when(
        diag_malaria_rdt_positive_clean == TRUE ~ TRUE,
        L0_q227_rdt_result == "Positive" ~ TRUE,
        L0_q227_rdt_result == "Negative" ~ FALSE,
        TRUE ~ NA
      ) %>% as.factor()) %>%

      #diarrhea
      mutate(symptom15dys_diarrhea_clean = case_when(
        L0_q94_diarrhea_now_15days == "Yes" ~ TRUE,
        L0_q94_diarrhea_now_15days == "No" ~ FALSE,
        L0_q94_diarrhea_now_15days == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) %>%

      #fever
      mutate(symptom15dys_fever_clean = case_when(
        L0_q117_fever_now_15days == "Yes" ~ TRUE,
        L0_q117_fever_now_15days == "No" ~ FALSE,
        L0_q117_fever_now_15days == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) %>%

      # emesis
      mutate(symptom15dys_vomit_clean = case_when(
        L0_q137_vomit_now_15days == "Yes" ~ TRUE,
        L0_q137_vomit_now_15days == "No" ~ FALSE,
        L0_q137_vomit_now_15days == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) %>%

      # headache
      mutate(symptom15dys_headache_clean = case_when(
        L0_q236_headache_15days == "Yes" ~ TRUE,
        L0_q236_headache_15days == "No" ~ FALSE,
        L0_q236_headache_15days == "." ~ NA,
        TRUE ~ NA
      ) %>% as.factor()) -> cohort_2020_anthro_
      
    cohort_2020_anthro_ %>%
      filter(!deleted) %>%
      filter(L0_q813_who_are_you_following_up_with_individual_id != ".") %>%
      filter(L0_q38_date_followup != ".") %>%
      mutate(uuid_clean = str_c(
        L0_q813_who_are_you_following_up_with_individual_id, 
        L0_q856_unique_id_if_unable_to_select_from_dropdown_above, 
        sep = "_")) %>%
      filter(uuid_clean != "._") %>%
      rowwise() %>%
      mutate(uuid_clean = generate_uid(salt=Sys.getenv("UUID_SALT"), uuid_clean)) %>%
      ungroup() %>%
      group_by(uuid_clean) %>%
      arrange(uuid_clean, date_clean) %>%
      mutate(followup_number_clean = row_number()) %>%
      ungroup() %>%
      mutate(across(contains("diag_"), ~ case_when(
        . == "." ~ NA,
        is.na(.) ~ NA,
        TRUE ~ TRUE
      ) %>% as.factor())) %>%
      rename(village_clean = L0_q791_enumerator) %>%
      select(contains('clean')) %>%
      select(-contains("L0")) %>%
      select(uuid_clean, followup_number_clean, date_clean, village_clean, everything())
}
