# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

#' Process Visual Deformities Data
#'
#' This function harmonizes and cleans deformity-related health data collected from
#' two columns: `visual_health_deformities` and `other_visual_health_deformities`.
#' It merges the two sources, removes placeholder text, translates free-text values
#' into standardized English terms, and returns a new column `deformities_clean`.
#'
#' Specific cleaning steps include:
#' - Merging both `visual_health_deformities` and `other_visual_health_deformities` when both are present
#' - Lowercasing and removing prefixes like "other deformities, "
#' - Translating common Malagasy or ambiguous phrases into standardized terms:
#'     - `"balana"` → `"strabismus"`
#'     - `"simba maso ilany"` → `"one_eye_non_functional"`
#'     - `"tongotra"` → `"malformed_foot"`
#'     - `"kondohalitry"` → `"severe_bowleggedness"`
#'     - `"missing teeth"` → `"missing_teeth"`
#'
#' @param df A data frame containing the columns `visual_health_deformities` and `other_visual_health_deformities`.
#'
#' @return A modified data frame with an added `deformities_clean` character column, containing cleaned and translated deformity labels.
#'
#' @export
#'
#' @examples
#' df <- tibble(
#'   visual_health_deformities = c("Balana", "Simba maso ilany", NA),
#'   other_visual_health_deformities = c(NA, "Tongotra", "Kondohalitry, moa")
#' )
#' process_deformities(df)
process_deformities <- function(df){
    
    df %>%
      mutate(  
        deformities_clean = case_when(
              is.na(visual_health_deformities)              ~ NA_character_,
              visual_health_deformities == "Deformities na" ~ NA_character_,
              !is.na(visual_health_deformities) & !is.na(other_visual_health_deformities) ~ str_c(visual_health_deformities, ", ", other_visual_health_deformities),
              TRUE ~ visual_health_deformities
        ) %>%
          #start translations here
          str_to_lower() %>%
          str_remove("other deformities, ") %>%
          #special case
          str_replace("missing teeth, ", "missing_teeth") %>%
          #special case
          str_replace("kondohalitry, moa", "severe_bowleggedness,mute") %>%
          str_replace("simba maso ilany", "one_eye_non_functional") %>%
          str_replace("balana", "strabismus") %>%
          str_replace("tongotra", "malformed_foot") %>%
          str_replace(" ", "_")
      )
}
